### ISSUE TITLE
Potential math error in exponential coalescent

### ISSUE THREAD

**Issue by m-a-martin** [nicfel/Mascot#12]
Hi Dr. Müller, 

Really sorry if I'm mistaken here, but I think there might be an error in the math in the getNeTime function in mascot.parameterdynamics.ExponentialNe, although it's possible I'm misunderstanding how the parameters are defined. 

If NeNull is the population size at the most recent calendar time and getNeTime is supposed to return the population size at time t in the past then I think it should be NeNull * Math.exp(-t*growthRate). 

E.g. with a growth rate of 0.25 and a NeNull of 100 you would expect the population size 10 years in the past to be 100*exp(-0.25 * 10) = 8.2. 

This is how (what I presume is) the [analogous function](https://github.com/CompEvol/beast2/blob/f07028669a3378477eff0213dd59b0222725be8e/src/beast/base/evolution/tree/coalescent/ExponentialGrowth.java) in the regular exponential coalescent function is written. 

Again, if I'm misunderstanding I apologize, but I can't wrap my head around the function as written. 

https://github.com/nicfel/Mascot/blob/43100a5df3dae2a9acc8dea8c005c81cd84ec770/src/mascot/parameterdynamics/ExponentialNe.java#L34

**Comment by m-a-martin** [comment]
Hi Dr. Muller, 

I wanted to follow up about this question. To test my intuition, I fit both the Mascot exponential coalescent and the standard exponential coalescent models to the pandemic H1N1 dataset from the [beast.community tutorial ](https://beast.community/phylodynamics_of_epidemic_influenza). 

The standard exponential coalescent ends up with parameter estimates very similar to the tutorial, with a mean pop size of ~16 and a  growth rate of ~21.5. 
<img width="400" alt="Screenshot 2024-05-02 at 9 08 41 PM" src="https://github.com/nicfel/Mascot/assets/29783515/33b54b52-db26-4a17-9fd2-47fc69ad29b4">

Using the MASCOT skyline coalescent with exponential dynamics, however, the pop size parameter is estimated to be much lower, ~2.2. 
<img width="398" alt="Screenshot 2024-05-02 at 9 08 34 PM" src="https://github.com/nicfel/Mascot/assets/29783515/1673b1bd-86c3-4811-b590-a7d1642cef4d">

It's possible I am misunderstanding how the model is defined, but at least based on the code comments and the MASCOT skyline manuscript the population size parameters for both models is the population size at the most recent sampling time, so they should be analogously defined. With only a single deme I would expect them to give similar results. I've attached the XML file used for the MASCOT analysis. 


[H1N1pdm_2009_mascot.zip](https://github.com/nicfel/Mascot/files/15195431/H1N1pdm_2009_mascot.zip)

**Edit:** After looking at this more and looking through the source code for other parametric Ne models built into Mascot, I've realized that my confusion stems from the fact that NeNull is actually Log(Ne). Apologies for not picking up on this. This is clarified in the [constant Ne model code](https://github.com/nicfel/Mascot/blob/3440a45a206fbe2e8bcfdaa856b3ff54fe4497a9/src/mascot/parameterdynamics/ConstantNe.java#L10), but not for the exponential. It may be worth clarifying in the code or documentation somewhere, IMO, as this is a departure from other BEAST models, at least in my experience. minNe is also *not* defined on the log scale, which I at least find to be confusing.

**Comment by rbouckaert** [comment]
@m-a-martin I noticed that the default prior on growth rate for the coalescent with exponential growth is Laplace(mu=0.001, scale=0.5) while for Mascot it is Laplace(mu=0.001, scale=100), which perhaps can have an impact as well. It is always quite tricky comparing similar looking models.

**Comment by m-a-martin** [comment]
@rbouckaert great catch, I meant to double check that. regardless, after realizing the parameter in MASCOT is log(Ne) I think everything is fine in the code.

**Comment by nicfel** [comment]
Hi @m-a-martin, Apologies for the late response. 

I'll change the logging of the NeNull to logNeNull in the next release.

Best,
Nicola

**Comment by alexeid** [comment]
Maybe the code should have explicit in the comments what the parameterisation is? Especially since it is different from the constant case!
